### ISSUE TITLE
Decouple Emoj VM into a separate node module and publish it to npm 

### ISSUE THREAD

**Issue by ythecombinator** [robotlolita/emoj#1]
Hey I just loved *emoj*–cause, after all, who wouldn't love such 🔝👌😂 language?

I was wondering how cool it'd be to have its *REPL* right on my terminal. Although it is designed for the browser, I still can't see any reasons why keep the [VM code](https://github.com/robotlolita/emoj/blob/master/src/vm.js) tied to the online *REPL* and *Docs* code. 

Wouldn't it be nice to have a separate node module containing just the *VM*–and all the stuff related to the lang implementation itself, e.g. the parser–, and use it inside this project?–as well as in the REPL I intend to build?

> Yeah, I thought about `npm install -s emoj` but: 
	1. the current project isn't publish to *npm* 
	2. it'd bring much more code than what's actually necessary.

**Comment by robotlolita** [comment]
It was mostly an April's Fool thing, so I don't plan on working on it (and I don't really have the time to). Feel free to fork it and publish to npm though :)
